---
- name: install packages
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - php
    - php-mysql
    - git
    - tomcat
    - tomcat-webapps
    - tomcat-admin-webapps 
- name: start and enable service
  service: name=httpd state=started
- name: start and enable 
  service: name=tomcat state=started
